# Generated by Django 3.0.8 on 2021-01-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Claves',
            new_name='Clave',
        ),
    ]
