# Generated by Django 3.0.8 on 2021-01-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210131_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clave',
            name='passwordtwo',
            field=models.CharField(max_length=50),
        ),
    ]
