# Generated by Django 3.0.8 on 2021-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210131_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clave',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
