# Generated by Django 3.0.8 on 2021-01-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210131_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='clave',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
